### ISSUE TITLE
クラスの空ファイル追加

### ISSUE THREAD

**Issue by apochi** [tasuku-neko/ChatServer#5]
クラスを追加

**Comment by apochi** [comment]
import java.io._;
import java.net._;
import java.util.*;

public class ChatClientHandler extends Thread{

}

**Comment by apochi** [comment]
何も書かれていないファイルを変更

**Comment by tasuku-neko** [comment]
チャットサーバの作成#4 と統合したため、クラスの空ファイル追加#5は close します。
