### ISSUE TITLE
関数追加

### ISSUE THREAD

**Issue by apochi** [tasuku-neko/ChatServer#9]
ChatClientHandler.javaに関数を追加した。
   private Socket socket;
    private BufferedReader in;
    private BufferedWriter out;
    private String name;
    private int num;
    private int usernum;
    static Map map = new TreeMap();
    static List userlist = new ArrayList();

**Comment by tasuku-neko** [comment]
どのような関数なのか明記して欲しいです。

**Comment by tasuku-neko** [comment]
現時点で不要、また追加が出来ていないため close します。
